services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://localhost:8081
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8081:8080"
  apigateway:
    container_name: apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: src/Services/UserService/Dockerfile

  user-service-db:
    container_name: user-service-db
    image: postgres

  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: src/Services/ProductService/Dockerfile

  product-service-db:
    container_name: product-service-db
    image: postgres

  cart-service:
    container_name: cart-service
    build:
      context: .
      dockerfile: src/Services/CartService/Dockerfile

  cart-service-db:
    container_name: cart-service-db
    image: postgres

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: src/Services/OrderService/Dockerfile

  order-service-db:
    container_name: order-service-db
    image: postgres

  payment-service:
    container_name: payment-service
    build:
      context: .
      dockerfile: src/Services/PaymentService/Dockerfile

  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: src/Services/NotificationService/Dockerfile

  notification-service-db:
    container_name: notification-service-db
    image: postgres

  distributed-cache:
    container_name: distributed-cache
    image: redis

  message-broker:
    container_name: message-broker
    image: rabbitmq:management

volumes:
  user_service_postgres_data:
  product_service_postgres_data:
  cart_service_postgres_data:
  order_service_postgres_data:
  notification_service_postgres_data:
